### PR TITLE
Improve infocus ui

### PR DESCRIPTION
**Pull request by hollanderbart**
This will resolve the #14 bug and will improve the user experience. It will now only show a previous of the channel when it is in focus.

### CODE REVIEW

**Comment by hollanderbart** [comment]
also resolved #12

**Comment by FokkeZB** [comment]
@hollanderbart thanks!

I gave this a try, but ran into:

```
dyld: Library not loaded: @rpath/NPOStream.framework/NPOStream
  Referenced from: /var/containers/Bundle/Application/945A8861-027C-402D-AE27-50742B7120D5/NPO Live.app/NPO Live
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/945A8861-027C-402D-AE27-50742B7120D5/NPO Live.app/Frameworks/NPOStream.framework/NPOStream: required code signature missing for '/private/var/containers/Bundle/Application/945A8861-027C-402D-AE27-50742B7120D5/NPO Live.app/Frameworks/NPOStream.framework/NPOStream'

	/private/var/containers/Bundle/Application/945A8861-027C-402D-AE27-50742B7120D5/NPO Live.app/Frameworks/NPOStream.framework/NPOStream: required code signature missing for '/private/var/containers/Bundle/Application/945A8861-027C-402D-AE27-50742B7120D5/NPO Live.app/Frameworks/NPOStream.framework/NPOStream'

	/private/var/containers/Bundle/Application/945A8861-027C-402D-AE27-50742B7120D5/NPO Live.app/Frameworks/NPOStream.framework/NPOStream: required code signature missing for '/private/var/containers/Bundle/Application/945A8861-027C-402D-AE27-50742B7120D5/NPO Live.app/Frameworks/NPOStream.framework/NPOStream'
```

I did run `pod install`. I'm on Xcode 9.3 and run tvOS 11.3.

**Comment by FokkeZB** [comment]
I fixed it by setting this setting:

**Comment by hollanderbart** [comment]
Ok, I will fix that. Thanks for mentioning FokkeZB. Much appreciated!!
But the big question is, does it work better now?

**Comment by FokkeZB** [comment]
It does! I did notice some lag when going through the menu. Perhaps there should be some delay before loading the stream to prevent that?

**Comment by hollanderbart** [comment]
Needs a lot more testing though. I’m looking for users who are willing to test this before I want to release a next version.

**Comment by hollanderbart** [comment]
Good point. I was already thinking about this as a possible solution. But it already avoids the loading spinner screens by only presenting the preview when the video buffer is full. Maybe I can check/verify if the video buffering is done on the background.

**Pull request merged**
